server:
  port: 9000

spring:
  application:
    name: learn
  http: # upload file
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
      location: /data/tmpUpload # update temp dir